### ISSUE TITLE
Skema for kun en bestemt dag?

### ISSUE THREAD

**Issue by danielkp1234** [fredrikj31/LectioScraper#12]
Hej, jeg er ved at prøve at lave et program der finder sluttidspunktet på den sidste time, men jeg har meget svært ved at separeret dagene eftersom at fullSchedule bare returnere alle timer i en lang liste, men ikke separeret efter dage.

Er det muligt at jeg kan skaffe skemaet kun for en bestemt dag og sidste time.

@fredrikj31

**Comment by fredrikj31** [comment]
Hej @danielkp1234 

Jeg er desværre gået ud af gymnasiet, og kan derfor ikke selv teste systemet mere. Men kan du evt lægge output'et ud i en pastebin eller et sted hvor jeg kan se det. Tænker nemlig at man kan lave noget magi ved data'en via json.

**Comment by danielkp1234** [comment]
Hej @fredrikj31 

Her er outputted af 
lec = Lectio("","","")
jsonify(lec.getSchedule())
https://pastebin.com/zEq3qkWT

Jeg vil egentlig bare have noget der giver mig slut tidspunktet på sidste modul for den nuværende dag som jeg kan benytte i min flask rest api, men problemet er bare at jeg har svært ved at regne ud hvordan at jeg skal gøre så at den kun viser sidste modul for den nuværende dag.

**Comment by fredrikj31** [comment]
Altså du kan jo dele det fulde array op i flere små arrays så du fordeler dem ud via "Day" variablen. Dernæst så tager du bare det sidste element i listen. Det burde være den sidste time.

**Comment by danielkp1234** [comment]
(Glemte lige at nævne at jeg har ændret lidt i schedule.py det her er min version https://pastebin.com/bbA5TjDs)

**Comment by danielkp1234** [comment]
> Altså du kan jo dele det fulde array op i flere små arrays så du fordeler dem ud via "Day" variablen. Dernæst så tager du bare det sidste element i listen. Det burde være den sidste time.

Og det er som jeg har forsøgt at jeg regne hvordan jeg gør i lidt for lang tid nu 😅

Kan nemlig ikke finde ud af at dele arrayet op efter de forskellige dage

**Comment by fredrikj31** [comment]
@danielkp1234  Fandt en lille code snippet som kan hjælpe dig med at gøre det. Her gør den egentlig bare at den gruppere alle elementer med samme dag sammen i et array, dermed kan du teknisk set bare tage det sidste element i hvert array, det er den sidste time hver dag.

Her er linket til der hvor jeg har fundet koden: [https://www.geeksforgeeks.org/group-list-of-dictionary-data-by-particular-key-in-python/](https://www.geeksforgeeks.org/group-list-of-dictionary-data-by-particular-key-in-python/)

Og her kan du se hele min snippet, med data'en også: [https://gist.github.com/fredrikj31/3a97174e3a0a9fad6119f559a81f140b](https://gist.github.com/fredrikj31/3a97174e3a0a9fad6119f559a81f140b)

Håber det kan hjælpe :)

**Comment by fredrikj31** [comment]
> > Altså du kan jo dele det fulde array op i flere små arrays så du fordeler dem ud via "Day" variablen. Dernæst så tager du bare det sidste element i listen. Det burde være den sidste time.
> 
> Og det er som jeg har forsøgt at jeg regne hvordan jeg gør i lidt for lang tid nu 😅
> 
> Kan nemlig ikke finde ud af at dele arrayet op efter de forskellige dage

@danielkp1234 Har du nogle opdatering, har du fået det til at virke eller dur det bare ikke 😂
