### ISSUE TITLE
Fejl i RegEX expression til at hente skema.

### ISSUE THREAD

**Issue by danielkp1234** [fredrikj31/LectioScraper#13]
Hej igen.

Jeg har siddet og debugget for at prøve at finde ud af hvorfor at funktionen til at hente skemaet virkert for mig sidste gang, men ikke længere og jeg har fundet frem til noget interssant. 

Hvis vi kigger i schedule.py på linje 40 står der 
timeStructure = re.compile('\d{2}/\d+-\d{4} \d{2}:\d{2} til \d{2}:\d{2}')

Den her expression ville vel ikke virke hvis at datoen ikke har 2 cifre.
Så problemet med hvorfor det ikke virker for mig ville jeg tro kunne have noget at gøre med at for at match expression skal datoen have 2 cifre altså vil datoer før den 10. ikke match.

Jeg har bare ingen forstand på hvordan RegEX expressions fungerer så er ikke helt sikker på hvordan man fikser det her så den tænker 1 eller 2 cifre i datoen så det er ligegyldigt om det er den 8. i måneden eller den 10.

**Comment by fredrikj31** [comment]
Hej Daniel.

Har du nogle former for screenshot, hvor der eventuelt er en dato på, som kan være med til at breake systemet. Har ikke selv adgang til Lectio mere, fordi jeg er gået ud af Gymnasiet, så har lidt svært ved at teste det. Kan du vedhæfte sådan et screenshot, så jeg kan kigge videre på RegEx expression'en?

**Comment by danielkp1234** [comment]
Her er en dato der f.eks. ikke virker
7/11-2022 10:15 til 11:15
men 
17/11-2022 10:15 til 11:15
virker fint
![image](https://user-images.githubusercontent.com/19412591/201201980-349a9d10-889d-4bb1-9c9c-520ad10d4560.png)
![image](https://user-images.githubusercontent.com/19412591/201202037-f1d4a466-7dbf-4db2-949a-36c5681164f1.png)
![image](https://user-images.githubusercontent.com/19412591/201202071-bb9d4b5e-da65-4eff-b8e8-733d82b6bfb1.png)


matcher regex expressionen

**Comment by danielkp1234** [comment]
En anden ting.
Jeg har stadig svært ved at få den til at sorterer efter dato og give mig tidspunktet på sidste time på den nuværende dag.
Her er min kode. 
![image](https://user-images.githubusercontent.com/19412591/201203947-a7663e05-225c-4bb2-b8bb-8666df467715.png)
Giver et tomt output somehow

Her er json data som jeg prøver at behandle så jeg kun for slut tidspunktet for sidste time på den nuværende dag.
https://pastebin.com/rCaDkxhk
Bemærk hvordan at den første del mangler Time og Day data hvilket skyldes fejlen i regex expressionen som vidst ovenfor hvilket gør at den ikke kan finde tid og dato

**Comment by fredrikj31** [comment]
> Her er en dato der f.eks. ikke virker 7/11-2022 10:15 til 11:15 men 17/11-2022 10:15 til 11:15 virker fint ![image](https://user-images.githubusercontent.com/19412591/201201980-349a9d10-889d-4bb1-9c9c-520ad10d4560.png) ![image](https://user-images.githubusercontent.com/19412591/201202037-f1d4a466-7dbf-4db2-949a-36c5681164f1.png) ![image](https://user-images.githubusercontent.com/19412591/201202071-bb9d4b5e-da65-4eff-b8e8-733d82b6bfb1.png)
> 
> matcher regex expressionen

For at kunne få fixet regex expression'en, så kan du ændre den til følgende:
`\d+\/\d+-\d{4} \d{2}:\d{2} til \d{2}:\d{2}`

Dette gør er bare at erstatte det første check til at checke hvis der er 1 eller flere tal, som den næste også gør. Så den bruge virke, til at fange alle dage. Det er min fejl, da jeg lavede programmet at den ikke checker for det.

**Comment by fredrikj31** [comment]
> En anden ting. Jeg har stadig svært ved at få den til at sorterer efter dato og give mig tidspunktet på sidste time på den nuværende dag. Her er min kode. ![image](https://user-images.githubusercontent.com/19412591/201203947-a7663e05-225c-4bb2-b8bb-8666df467715.png) Giver et tomt output somehow
> 
> Her er json data som jeg prøver at behandle så jeg kun for slut tidspunktet for sidste time på den nuværende dag. https://pastebin.com/rCaDkxhk Bemærk hvordan at den første del mangler Time og Day data hvilket skyldes fejlen i regex expressionen som vidst ovenfor hvilket gør at den ikke kan finde tid og dato

Hvis regex gør at dato og tid også kommer med på alle dage, så kan du bruge den her snippet til at få sorteret timerne indtil dage, så kan du bare tage det sidste element i hvert array, som gerne burde være den sidste time på dagen.

```python
from itertools import groupby

# Online Python compiler (interpreter) to run Python online.
# Write Python 3 code in this online editor and run it.
# define a function for key
def key_func(k):
    return k['Day']
 
# sort INFO data by 'company' key.
data = sorted(data, key=key_func)
 
for key, value in groupby(data, key_func):
    print(list(value))
```

**Comment by danielkp1234** [comment]
> > En anden ting. Jeg har stadig svært ved at få den til at sorterer efter dato og give mig tidspunktet på sidste time på den nuværende dag. Her er min kode. ![image](https://user-images.githubusercontent.com/19412591/201203947-a7663e05-225c-4bb2-b8bb-8666df467715.png) Giver et tomt output somehow
> > Her er json data som jeg prøver at behandle så jeg kun for slut tidspunktet for sidste time på den nuværende dag. https://pastebin.com/rCaDkxhk Bemærk hvordan at den første del mangler Time og Day data hvilket skyldes fejlen i regex expressionen som vidst ovenfor hvilket gør at den ikke kan finde tid og dato
> 
> Hvis regex gør at dato og tid også kommer med på alle dage, så kan du bruge den her snippet til at få sorteret timerne indtil dage, så kan du bare tage det sidste element i hvert array, som gerne burde være den sidste time på dagen.
> 
> ```python
> from itertools import groupby
> 
> # Online Python compiler (interpreter) to run Python online.
> # Write Python 3 code in this online editor and run it.
> # define a function for key
> def key_func(k):
>     return k['Day']
>  
> # sort INFO data by 'company' key.
> data = sorted(data, key=key_func)
>  
> for key, value in groupby(data, key_func):
>     print(list(value))
> ```

Okay, det er også det som at jeg gør som du kan se på screenshotet, men hvordan fikser jeg regex expression så fatter at det er ligegyldigt at der ikke er 2 tal som feks 11 og så at det også virker med datoer frem til den 10. altså 1 cifre

**Comment by fredrikj31** [comment]
Hvis du erstartter den regex expression som fejler til den her expression så burde det virke:
`\d+\/\d+-\d{4} \d{2}:\d{2} til \d{2}:\d{2}`

**Comment by fredrikj31** [comment]
Fik du det her til at virke, eller er der opstået flere fejl? Du må gerne genåbne det her issue, hvis der er kommet opdateringer :)
