### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by juliangudmundsson** [fredrikj31/LectioScraper#9]
im trying to run a test and it throws this error

![image](https://user-images.githubusercontent.com/99136896/152691899-66b891eb-844d-4de7-8181-27a99b76e591.png)

im new to python so i dont know what the reason is

have tried to call the function without the return variable and its the same, so its probably not part of the issue

**Comment by fredrikj31** [comment]
What test are you trying to run?

**Comment by juliangudmundsson** [comment]
test_schedule.py

it has a line "from tests.details import lectioUsername, lectioPassword, schoolId" that refers to a file "details"

this is not in the folders

so i have just hardcoded the username, pwd, schoolid

i could not get "pip install LectioScraper" to work, it responds "ERROR: Could not find a version that satisfies the requirement LectioScraper (from versions: none)
ERROR: No matching distribution found for LectioScraper"

im on windows 10 but have also tried on the Ubuntu subsystem with same result

so i have just downloaded the files from git as a zip and unpacked them

**Comment by fredrikj31** [comment]
Okay, så you will neee to create the details.py file inside the tests directory.

The file's content should look like this
```python
# details.py
lectioUsername = "username here..."
lectioPassword = "password here..."
schoolId = "school id here..."
```

All the variables should be strings, also the id.
